{% set name = "SpydrPick" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower}}
  version: {{ version }}

source:
  url: https://github.com/santeripuranen/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: b8f6e839920173f33eb2aea002d618cdab240db18165782d6c40694d0f30936f

build:
  skip: True #  [osx]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - python <3
  host:
    - tbb
    - curl

test:
  commands:
    - SpydrPick
    - aracne

about:
   home: https://github.com/santeripuranen/SpydrPick
   license: GNU Affero General Public License
   license_file: LICENSE
   summary: Mutual information based detection of pairs of genomic loci co-evolving under a shared selective pressure

extra:
   identifiers:
     - doi:10.1101/523407
