{% set name = "nimnexus" %}
{% set version = "0.1.1" %}
{% set revision = "f99eaf1" %}
{% set sha256hash = "3e0656e02cbd3222e0b302681f26f478717aa4ad69e6b13ceaafff498c23ca2a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/avsecz/{{ name }}/archive/{{ revision }}.tar.gz
  sha256: {{ sha256hash }}

build:
  number: 2
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pcre
    - htslib
  run:
    - pcre
    - htslib

test:
  commands:
    - nimnexus trim -h
    - nimnexus dedup -h
    
about:
  home: https://github.com/avsecz/nimnexus
  license: MIT
  summary: command-line tools for processing ChIP-nexus data
