{% set version = "2.5.0" %}

package:
  name: nlopt
  version: {{ version }}

build:
  number: 1

source:
  url: https://github.com/stevengj/nlopt/archive/v{{version}}.tar.gz
  sha256: c6dd7a5701fff8ad5ebb45a3dc8e757e61d52658de3918e38bab233e7fd3b4ae

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - cmake

test:
  commands:
    - "ls ${PREFIX}/lib/libnlopt.a"

about:
  home: https://nlopt.readthedocs.io/en/latest/
  license: LGPL license
  summary: Library for non-linear optimization
