{% set version = "1.0.1a" %}

package:
  name: dammet
  version: {{ version }}

build:
  number: 1

source:
  # url: https://gitlab.com/KHanghoj/DamMet/-/archive/master/DamMet-master.tar.gz
  url: https://gitlab.com/KHanghoj/DamMet/-/archive/{{ version }}/DamMet-{{ version }}.tar.gz
  sha256: 5fa27cb20ba45b269b47e33d5aea2ebe1cc634f836b5ea01834512ba4df87df4
  # 16dbb2dd9a22d3b78add71aa5673e1a963ca91718d800ee49dd5446f67961018

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - ncurses
    - zlib
    - bzip2
    - curl
    - xz
    - libdeflate
    - wget
    - cmake
    - tar
    - htslib
    - nlopt
  run:
    - zlib
    - ncurses
    - zlib
    - bzip2
    - curl
    - xz
    - libdeflate
    - htslib
    - nlopt
about:
  home: https://gitlab.com/KHanghoj/DamMet
  license: MIT license
  summary: Software to reconstruct methylomes from HTS data underlying and ancient specimen

test:
  commands:
    - DamMet
