{% set version = "1.0.1" %}

package:
  name: dammet
  version: {{ version }}

build:
  number: 1

source:
  # url: https://gitlab.com/KHanghoj/DamMet/-/archive/master/DamMet-master.tar.gz
  url: https://gitlab.com/KHanghoj/DamMet/-/archive/{{ version }}/DamMet-{{ version }}.tar.gz
  sha256: 5b8148999c75399e587a8a821724cc1c73dfceb182a989630b5b78bf617e6101

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - ncurses
    - zlib
    - bzip2
    - curl
    - xz
    - libdeflate
    - wget
    - cmake
    - tar
    - htslib
  run:
    - zlib
    - ncurses
    - zlib
    - bzip2
    - curl
    - xz
    - libdeflate
    - htslib
about:
  home: https://gitlab.com/KHanghoj/DamMet
  license: MIT license
  summary: Software to reconstruct methylomes from HTS data underlying and ancient specimen

test:
  commands:
    - DamMet
